import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Portfolio from '../components/Portfolio'

export default function Home() {
  return (
    <div className='font-dm-sans bg-primary-color dark:bg-slate-800 dark:text-white'>
      <Head>
        <title>Mohamed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className='z-10 bg-transparent sticky top-0 w-full'>
        <Navbar />
      </header>

      <main className='flex flex-col gap-10 lg:gap-16'>
        <Header />
        <About />
        <Portfolio />
      </main>
      
      <footer>

      </footer>
    </div>
  )
}
