import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className='font-dm-sans h-[400vh] bg-primary-color'>
      <Head>
        <title>Mohamed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='z-10 bg-transparent sticky top-0 w-full'>
        <Navbar />
      </header>

      <main>
        <Header />
      </main>
      
      <footer>

      </footer>
    </div>
  )
}
